TRUNCATE TABLE VISITEVARCHI;
TRUNCATE TABLE VISITE;
TRUNCATE TABLE VARCHI;
TRUNCATE TABLE ABBONAMENTI;
TRUNCATE TABLE BIGLIETTI;
TRUNCATE TABLE TITOLIINGRESSO;
TRUNCATE TABLE TIPOLOGIEINGRESSOMUSEI;
TRUNCATE TABLE TIPOLOGIEINGRESSO;
TRUNCATE TABLE NEWSLETTERUTENTI;
TRUNCATE TABLE NEWSLETTER;
TRUNCATE TABLE TUTORI;
TRUNCATE TABLE UTENTIPAGAMENTI;
TRUNCATE TABLE PAGAMENTICAMPIESTIVI;
TRUNCATE TABLE UTENTIMUSEO;
TRUNCATE TABLE UTENTICAMPIESTIVI;
TRUNCATE TABLE UTENTI;
TRUNCATE TABLE TARIFFECAMPIESTIVI;
TRUNCATE TABLE CAMPIESTIVI;
TRUNCATE TABLE DESCRIZIONI;
TRUNCATE TABLE AUTORIOPERE;
TRUNCATE TABLE AUTORI;
TRUNCATE TABLE SALEOPERE;
TRUNCATE TABLE AMBIENTIDISERVIZIO;
TRUNCATE TABLE SALE;
TRUNCATE TABLE STANZE;
TRUNCATE TABLE OPERE;
TRUNCATE TABLE MUSEI;


-- not in official documentation, see:
-- https://web.archive.org/web/20211015201544/http://stackoverflow.com/questions/51470/how-do-i-reset-a-sequence-in-oracle/
ALTER SEQUENCE IdMuseoSeq RESTART START WITH 1;
ALTER SEQUENCE IdOperaSeq RESTART START WITH 1;
ALTER SEQUENCE IdStanzaSeq RESTART START WITH 1;
ALTER SEQUENCE IdMovimentoSeq RESTART START WITH 1;
ALTER SEQUENCE IdAutoreSeq RESTART START WITH 1;
ALTER SEQUENCE IdDescSeq RESTART START WITH 1;
ALTER SEQUENCE IdCampiEstiviSeq RESTART START WITH 1;
ALTER SEQUENCE IdTariffaSeq RESTART START WITH 1;
ALTER SEQUENCE IdUtenteSeq RESTART START WITH 1;
ALTER SEQUENCE IdPagamentoSeq RESTART START WITH 1;
ALTER SEQUENCE IdNewsSeq RESTART START WITH 1;
ALTER SEQUENCE IdTipologiaingSeq RESTART START WITH 1;
ALTER SEQUENCE IdTitoloingSeq RESTART START WITH 1;
ALTER SEQUENCE IdVarchiSeq RESTART START WITH 1;
ALTER SEQUENCE IdVisiteSeq RESTART START WITH 1;
